version: "3"

services:
    mongodb:
        image: mongo:latest
        volumes: 
            - /docker-config/database:/db
        ports:
            - "27017:27017"
    restaurant-api:
        depends_on:
            - mongodb
        container_name: restaurant-api
        build: 
            context: ./
        image: restaurant-api:1.0
        volumes: 
            - "./:/var/www/app"
        links:
            - mongodb
        ports: 
            - "6350:6350"